### PR TITLE
Fixes output to file when multiple errors on different sources.

### PR DESCRIPTION
**Pull request by Cayan**
Only the last file with errors is being reported.

Updated version of @gronke's pull request (just the fix, without the tests)

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/grunt-tslint](https://github.com/palantir/grunt-tslint), @Cayan! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

**Comment by Cayan** [comment]
The result from the generated file is **not** a proper pmd file.

Generated sample:

`<pmd version="tslint"><file ...></file></pmd><pmd version="tslint"><file ...></file></pmd><pmd version="tslint"><file ...></file></pmd>...<pmd version="tslint"><file ...></file></pmd>`

**Comment by gronke** [comment]
#31 is rebased and cleaned (including the tests)

@Cayan thanks for reviving this. Do you have a suggestion how to fix the Jenkins import? Looks like a different issue than this PR attempts to solve..

**Comment by Cayan** [comment]
@gronke I'm working on it. This is a TSLint bug as well. Fixed here: https://github.com/palantir/tslint/pull/1493

**Comment by Cayan** [comment]
Jenkins successfully imported the reported PMD file with both PR's content.

**Comment by Cayan** [comment]
A previous PR was opened with the solution for the XML bug palantir/tslint/pull/1472, so I closed my PR there. Since this implementation needed palantir/tslint#1493, it will now be closed. A proper implementation should be created with the first strategy.

**Pull request closed without merging**
